### ISSUE TITLE
Unable to find view

### ISSUE THREAD

**Issue by atifshamim** [soundaranbu/Razor.Templating.Core#68]
Hi

I have below Project Structure and my .cshtml file is placed in below location and below line of code to locate the file but getting below error

<img width="826" alt="image" src="https://github.com/soundaranbu/Razor.Templating.Core/assets/96318323/3ea940b4-d221-4d1d-b9d3-9413087eca42">

Unable to find view '/PrintTicket/Views/PrintTicket.cshtml'. The following locations were searched:
/PrintTicket/Views/PrintTicket.cshtml
Hint:
- Check whether you have added reference to the Razor Class Library that contains the view files.
- Check whether the view file name is correct or exists at the given path.
- Refer documentation or file issue here: https://github.com/soundaranbu/RazorTemplating

Please note Application is not the startup project instead FlightApi is the start up project.

**Comment by soundaranbu** [comment]
Hey @atifshamim, How does your Application project's .csproj look like? 

Does it have all these?
```xml
<Project Sdk="Microsoft.NET.Sdk.Razor"> <PropertyGroup> <TargetFrameworks>net6.0</TargetFrameworks> <AddRazorSupportForMvc>true</AddRazorSupportForMvc> </PropertyGroup> <ItemGroup> <FrameworkReference Include="Microsoft.AspNetCore.App" /> </ItemGroup> </Project>
```

**Comment by atifshamim** [comment]
Thanks @soundaranbu ,

I just modified my .csproj file and it's working now

Changed from below version to next version

`<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>
  
 
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>`

**Next Version**


`<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Razor.Templating.Core" Version="1.9.0" />
  </ItemGroup>
  
  
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>`

**Comment by soundaranbu** [comment]
Closing this as the issue is resolved

**Comment by michaelakin** [comment]
Question, with .net 9, do we still have to change the project type to Razor?

I am getting this error and I have tried  using a separate "services" dll and  am still getting this error.

**Comment by soundaranbu** [comment]
Hey @michaelakin , yes the view files should be within the razor sdk type so that it can compile the razor views. Does it not work even then?

**Comment by michaelakin** [comment]
Thanks.  I added a seperate Razor assembly to hold my one template that we have so far and that worked great.  Thanks so much
